"""initial migration

Revision ID: 08c7859faa88
Revises: 
Create Date: 2026-06-29 23:19:47.693095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c7859faa88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='关联 Project.id（无物理外键）'),
    sa.Column('supplier_id', sa.String(length=36), nullable=False, comment='关联 Supplier.id（无物理外键）'),
    sa.Column('order_no', sa.String(length=100), nullable=False, comment='订单编号'),
    sa.Column('order_name', sa.String(length=200), nullable=True, comment='订单名称'),
    sa.Column('order_date', sa.Date(), nullable=True, comment='生成订单日期'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='订单金额含税（元）'),
    sa.Column('non_tax_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='订单金额不含税（元）'),
    sa.Column('erp_no', sa.String(length=100), nullable=True, comment='智慧工程ERP项目编号'),
    sa.Column('mobile_project_no', sa.String(length=100), nullable=True, comment='移动项目编号'),
    sa.Column('order_type', sa.String(length=50), nullable=True, comment='订单类型（工程施工/维护服务/设备采购/其他）'),
    sa.Column('mobile_contact', sa.String(length=100), nullable=True, comment='移动对接人'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='状态（待执行/执行中/已完成/已作废）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_project_id'), 'order', ['project_id'], unique=False)
    op.create_index(op.f('ix_order_supplier_id'), 'order', ['supplier_id'], unique=False)
    op.create_table('project',
    sa.Column('framework_name', sa.String(length=200), nullable=False, comment='框架合同名称'),
    sa.Column('sign_date', sa.Date(), nullable=True, comment='签订时间'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='合同开始时间'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='合同结束时间'),
    sa.Column('internal_or_external', sa.String(length=20), nullable=False, comment='集团内外'),
    sa.Column('project_type', sa.String(length=100), nullable=False, comment='项目类型'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_table('supplier_price',
    sa.Column('supplier_id', sa.String(length=36), nullable=False, comment='关联 Supplier.id'),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_price_id'), 'supplier_price', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_price_supplier_id'), 'supplier_price', ['supplier_id'], unique=False)
    op.create_table('vendor',
    sa.Column('name', sa.String(length=200), nullable=False, comment='供应商名称（法律主体）'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_vendor_id'), 'vendor', ['id'], unique=False)
    op.create_table('budget_adjustment',
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='项目 ID（外键 → project.id）'),
    sa.Column('adjustment_date', sa.Date(), nullable=True, comment='调整日期'),
    sa.Column('adjustment_reason', sa.String(length=500), nullable=True, comment='调整原因'),
    sa.Column('adjustment_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='调整金额（元，正数=调增，负数=调减）'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_adjustment_id'), 'budget_adjustment', ['id'], unique=False)
    op.create_index(op.f('ix_budget_adjustment_project_id'), 'budget_adjustment', ['project_id'], unique=False)
    op.create_table('cost_flow',
    sa.Column('order_id', sa.String(length=36), nullable=False, comment='订单 ID（外键 → order.id）'),
    sa.Column('cost_party', sa.String(length=200), nullable=True, comment='成本方（供应商 / 个人 / 内部等）'),
    sa.Column('cost_type', sa.String(length=100), nullable=False, comment='成本类型（如：施工费 / 材料费 / 管理费等）'),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='税率（百分比，如 9.0 表示 9%）'),
    sa.Column('taxable_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='成本金额含税（元）'),
    sa.Column('non_taxable_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='成本金额不含税（元）'),
    sa.Column('cost_subject', sa.String(length=200), nullable=True, comment='成本科目'),
    sa.Column('budget_item', sa.String(length=200), nullable=True, comment='对应预算项'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态（待支付 / 部分支付 / 已支付 / 已作废）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_flow_id'), 'cost_flow', ['id'], unique=False)
    op.create_index(op.f('ix_cost_flow_order_id'), 'cost_flow', ['order_id'], unique=False)
    op.create_table('income_flow',
    sa.Column('order_id', sa.String(length=36), nullable=False, comment='订单 ID（外键 → order.id）'),
    sa.Column('invoice_count', sa.Integer(), nullable=False, comment='开票次数'),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='税率（百分比，如 9.0 表示 9%）'),
    sa.Column('taxable_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='开票金额含税（元）'),
    sa.Column('non_taxable_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='开票金额不含税（元）'),
    sa.Column('invoice_date', sa.Date(), nullable=True, comment='开票时间'),
    sa.Column('invoice_no', sa.String(length=200), nullable=True, comment='发票号码'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态（待回款 / 部分回款 / 已回款 / 已作废）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_flow_id'), 'income_flow', ['id'], unique=False)
    op.create_index(op.f('ix_income_flow_order_id'), 'income_flow', ['order_id'], unique=False)
    op.create_table('project_budget',
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='项目 ID'),
    sa.Column('budget_type', sa.String(length=100), nullable=False, comment='预算类型'),
    sa.Column('labor_budget', sa.Numeric(precision=15, scale=2), nullable=False, comment='人工费预算'),
    sa.Column('material_budget', sa.Numeric(precision=15, scale=2), nullable=False, comment='材料费预算'),
    sa.Column('management_budget', sa.Numeric(precision=15, scale=2), nullable=False, comment='管理费预算'),
    sa.Column('gross_margin_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='毛利率'),
    sa.Column('preparation_date', sa.Date(), nullable=True, comment='编制日期'),
    sa.Column('preparer', sa.String(length=100), nullable=True, comment='编制人'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_budget_id'), 'project_budget', ['id'], unique=False)
    op.create_index(op.f('ix_project_budget_project_id'), 'project_budget', ['project_id'], unique=False)
    op.create_table('supplier',
    sa.Column('vendor_id', sa.String(length=36), nullable=False, comment='关联 Vendor.id'),
    sa.Column('name', sa.String(length=200), nullable=True, comment='供应商名称（冗余，方便展示）'),
    sa.Column('framework', sa.String(length=200), nullable=True, comment='所属框架'),
    sa.Column('framework_no', sa.String(length=100), nullable=False, comment='框架编号'),
    sa.Column('framework_start_date', sa.Date(), nullable=True, comment='框架开始时间'),
    sa.Column('framework_end_date', sa.Date(), nullable=True, comment='框架结束时间'),
    sa.Column('year', sa.Integer(), nullable=True, comment='年度'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_id'), 'supplier', ['id'], unique=False)
    op.create_table('supplier_year_price',
    sa.Column('vendor_id', sa.String(length=36), nullable=False, comment='关联 Vendor.id'),
    sa.Column('year', sa.Integer(), nullable=True, comment='年度'),
    sa.Column('laborer_unit_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='普工单价'),
    sa.Column('technician_unit_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='技工单价'),
    sa.Column('senior_technician_unit_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='高级技工单价'),
    sa.Column('special_work_type', sa.String(length=100), nullable=True, comment='特种作业工种'),
    sa.Column('special_work_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='特种作业单价'),
    sa.Column('comprehensive_unit_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='综合单价'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'year', name='uq_vendor_year')
    )
    op.create_index(op.f('ix_supplier_year_price_id'), 'supplier_year_price', ['id'], unique=False)
    op.create_table('collection',
    sa.Column('flow_id', sa.String(length=36), nullable=False, comment='收入流水 ID（外键 → income_flow.id）'),
    sa.Column('collection_date', sa.Date(), nullable=True, comment='回款日期'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='回款金额（元）'),
    sa.Column('receipt_no', sa.String(length=200), nullable=True, comment='收款凭证号'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['flow_id'], ['income_flow.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_flow_id'), 'collection', ['flow_id'], unique=False)
    op.create_index(op.f('ix_collection_id'), 'collection', ['id'], unique=False)
    op.create_table('payment',
    sa.Column('cost_id', sa.String(length=36), nullable=False, comment='成本流水 ID（外键 → cost_flow.id）'),
    sa.Column('payment_date', sa.Date(), nullable=True, comment='支付日期'),
    sa.Column('payee', sa.String(length=200), nullable=True, comment='支付对象'),
    sa.Column('voucher_no', sa.String(length=200), nullable=True, comment='支付凭证'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='支付金额（元）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['cost_id'], ['cost_flow.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_cost_id'), 'payment', ['cost_id'], unique=False)
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_cost_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_collection_id'), table_name='collection')
    op.drop_index(op.f('ix_collection_flow_id'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_supplier_year_price_id'), table_name='supplier_year_price')
    op.drop_table('supplier_year_price')
    op.drop_index(op.f('ix_supplier_id'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_project_budget_project_id'), table_name='project_budget')
    op.drop_index(op.f('ix_project_budget_id'), table_name='project_budget')
    op.drop_table('project_budget')
    op.drop_index(op.f('ix_income_flow_order_id'), table_name='income_flow')
    op.drop_index(op.f('ix_income_flow_id'), table_name='income_flow')
    op.drop_table('income_flow')
    op.drop_index(op.f('ix_cost_flow_order_id'), table_name='cost_flow')
    op.drop_index(op.f('ix_cost_flow_id'), table_name='cost_flow')
    op.drop_table('cost_flow')
    op.drop_index(op.f('ix_budget_adjustment_project_id'), table_name='budget_adjustment')
    op.drop_index(op.f('ix_budget_adjustment_id'), table_name='budget_adjustment')
    op.drop_table('budget_adjustment')
    op.drop_index(op.f('ix_vendor_id'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_index(op.f('ix_supplier_price_supplier_id'), table_name='supplier_price')
    op.drop_index(op.f('ix_supplier_price_id'), table_name='supplier_price')
    op.drop_table('supplier_price')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_order_supplier_id'), table_name='order')
    op.drop_index(op.f('ix_order_project_id'), table_name='order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
