"""add_erp_tables_phase5_v2

Revision ID: 28a6a05c23d6
Revises: 6d9964726e9d
Create Date: 2026-07-03 21:40:46.184505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a6a05c23d6'
down_revision: Union[str, Sequence[str], None] = '6d9964726e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_staging_flow',
    sa.Column('record_type', sa.String(length=30), nullable=False, comment='记录类型: income_expense / receivable / collection'),
    sa.Column('occur_date', sa.Date(), nullable=True, comment='发生日期'),
    sa.Column('erp_record_id', sa.String(length=100), nullable=True, comment='业务单号 / 凭证号（唯一约束，防重复导入）'),
    sa.Column('summary', sa.Text(), nullable=True, comment='摘要 / 概念说明（核心模糊匹配字段）'),
    sa.Column('raw_project_name', sa.String(length=300), nullable=True, comment='原始客户名称 / 项目名称'),
    sa.Column('amount_in', sa.Numeric(precision=15, scale=2), nullable=True, comment='贷方 / 实收 / 应收金额'),
    sa.Column('amount_out', sa.Numeric(precision=15, scale=2), nullable=True, comment='借方 / 支出金额'),
    sa.Column('matched_project_id', sa.Integer(), nullable=True, comment='匹配到的 FinanceDesk 项目 ID'),
    sa.Column('matched_order_id', sa.Integer(), nullable=True, comment='匹配到的 FinanceDesk 订单 ID'),
    sa.Column('match_status', sa.String(length=20), nullable=False, comment='匹配状态: pending 待匹配 / auto_matched 自动匹配 / manual_matched 人工确认'),
    sa.Column('source_file', sa.String(length=500), nullable=True, comment='来源文件名'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['matched_order_id'], ['order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_project_id'], ['project.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('erp_record_id'),
    sa.UniqueConstraint('erp_record_id', name='uq_erp_record_id')
    )
    op.create_index(op.f('ix_erp_staging_flow_id'), 'erp_staging_flow', ['id'], unique=False)
    op.create_index(op.f('ix_erp_staging_flow_record_type'), 'erp_staging_flow', ['record_type'], unique=False)
    op.create_table('project_keyword_mapping',
    sa.Column('keyword', sa.String(length=200), nullable=False, comment="提取的关键词（如'金茂大厦'）"),
    sa.Column('target_project_id', sa.Integer(), nullable=False, comment='关联的系统项目 ID'),
    sa.Column('match_type', sa.String(length=20), nullable=False, comment='规则来源: auto / manual'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['target_project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_keyword_mapping_id'), 'project_keyword_mapping', ['id'], unique=False)
    op.create_index(op.f('ix_project_keyword_mapping_keyword'), 'project_keyword_mapping', ['keyword'], unique=True)
    # SKIP: cost_flow FK and supplier_unit_price constraint (SQLite limitation)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SKIP: reverse of above (SQLite limitation)
    op.drop_index(op.f('ix_project_keyword_mapping_keyword'), table_name='project_keyword_mapping')
    op.drop_index(op.f('ix_project_keyword_mapping_id'), table_name='project_keyword_mapping')
    op.drop_table('project_keyword_mapping')
    op.drop_index(op.f('ix_erp_staging_flow_record_type'), table_name='erp_staging_flow')
    op.drop_index(op.f('ix_erp_staging_flow_id'), table_name='erp_staging_flow')
    op.drop_table('erp_staging_flow')
    # ### end Alembic commands ###
