"""add_fk_constraints_passive_deletes

Revision ID: 3fb73ee04ff2
Revises: 28a6a05c23d6
Create Date: 2026-07-04 00:01:42.076756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb73ee04ff2'
down_revision: Union[str, Sequence[str], None] = '28a6a05c23d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_flow', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cost_flow_supplier_id', 'supplier', ['supplier_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('erp_staging_flow', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_erp_record_id', ['erp_record_id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_order_project_id', 'project', ['project_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_order_supplier_id', 'supplier', ['supplier_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('supplier_price', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_supplier_price_supplier_id', 'supplier', ['supplier_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('supplier_unit_price', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_supplier_unit_year'), type_='unique')

    with op.batch_alter_table('supplier_year_price', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_supplier_year_price_supplier_id', 'supplier', ['supplier_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_year_price', schema=None) as batch_op:
        batch_op.drop_constraint('fk_supplier_year_price_supplier_id', type_='foreignkey')

    with op.batch_alter_table('supplier_unit_price', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_supplier_unit_year'), ['supplier_id', 'year'])

    with op.batch_alter_table('supplier_price', schema=None) as batch_op:
        batch_op.drop_constraint('fk_supplier_price_supplier_id', type_='foreignkey')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_supplier_id', type_='foreignkey')
        batch_op.drop_constraint('fk_order_project_id', type_='foreignkey')

    with op.batch_alter_table('erp_staging_flow', schema=None) as batch_op:
        batch_op.drop_constraint('uq_erp_record_id', type_='unique')

    with op.batch_alter_table('cost_flow', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cost_flow_supplier_id', type_='foreignkey')

    # ### end Alembic commands ###
