"""add_sys_dictionary_table

Revision ID: 6d9964726e9d
Revises: a2b2d43a9019
Create Date: 2026-07-03 18:50:29.991771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9964726e9d'
down_revision: Union[str, Sequence[str], None] = 'a2b2d43a9019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dictionary',
    sa.Column('category', sa.String(length=100), nullable=False, comment='字典分类'),
    sa.Column('value', sa.String(length=100), nullable=False, comment='选项值'),
    sa.Column('label', sa.String(length=200), nullable=True, comment='展示标签（为空时视为与 value 一致）'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序号'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'value', name='uq_dict_category_value')
    )
    op.create_index(op.f('ix_sys_dictionary_category'), 'sys_dictionary', ['category'], unique=False)
    op.create_index(op.f('ix_sys_dictionary_id'), 'sys_dictionary', ['id'], unique=False)
    op.create_foreign_key(None, 'cost_flow', 'supplier', ['supplier_id'], ['id'])
    op.drop_constraint(op.f('uq_supplier_unit_year'), 'supplier_unit_price', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_supplier_unit_year'), 'supplier_unit_price', ['supplier_id', 'year'])
    op.drop_constraint(None, 'cost_flow', type_='foreignkey')
    op.drop_index(op.f('ix_sys_dictionary_id'), table_name='sys_dictionary')
    op.drop_index(op.f('ix_sys_dictionary_category'), table_name='sys_dictionary')
    op.drop_table('sys_dictionary')
    # ### end Alembic commands ###
