"""add_supplier_id_to_cost_flow

Revision ID: 8b2ba5df4cfe
Revises: bbd668b8acf9
Create Date: 2026-07-01 10:37:00.009028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2ba5df4cfe'
down_revision: Union[str, Sequence[str], None] = 'bbd668b8acf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_flow', sa.Column('supplier_id', sa.Integer(), nullable=True, comment='关联供应商 ID（外键 → supplier.id）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_flow', 'supplier_id')
    # ### end Alembic commands ###
